config/routes.rb
Rails.application.routes.draw do
  root 'storefront#all_items'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  get 'index' => 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  get 'clear_cart' => 'cart#clear_cart'
  post 'delete_item' => 'cart#delete_item'
  post 'order_complete' => 'cart#order_complete'
  devise_for :users
  resources :products
  resources :charges
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:add_to_cart, :view_order, :clear_cart, :delete_item]
  before_action :set_line_item, only: :delete_item

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
  end

  def add_to_cart
    @order = current_order
    @order.save if @order.id.nil?
    session[:order_id] = @order.id

    line_item = @order.line_items.find_or_create_by(product_id: line_item_params['product_id'].to_i)
    if line_item.quantity.nil?
      line_item.update(quantity: line_item_params['quantity'].to_i)
    else
      line_item.update(quantity: line_item.quantity + line_item_params['quantity'].to_i)
    end

    line_item.update(order_id: @order.id)
    line_item.update(line_item_total: (line_item.quantity * line_item.product.price))
    redirect_back(fallback_location: root_path)
  end

  def view_order
    @line_items = current_order.line_items
  end

  def clear_cart
    current_order.line_items.delete_all
    redirect_back(fallback_location: root_path)
  end

  def delete_item
    current_order.line_items.find_by(product_id: params[:product_id]).delete
    view_order
    set_cart_count
    render :view_order
  end

  def checkout
    @order = current_order

    if(@order.line_items.length > 0)

      @order.subtotal = 0
      @order.line_items.each do |line_item|
        line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
        @order.order_items[line_item.product_id] = line_item.quantity
        @order.subtotal += line_item.line_item_total
      end

      @order.save
      @order.update(sales_tax: (@order.subtotal * 0.07))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))
      # @order_confirmation = @order

      session[:order_id] = nil
      set_cart_count
    end
  end

  private

    def line_item_params
      params.require(:line_item).permit(:product_id, :quantity, :order_id, :line_item_id)
    end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Order <%= @order.id %></h2>
<p>Let's Review Your Order:</p>
<% @order.line_items.each do |line_item| %>
  <ul>
    <li><%= line_item.product.name %></li>
    <li>Qty: <%= line_item.quantity.to_s %></li>
  </ul>
<% end %>

<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.subtotal %>
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %>
</p>

<p>
  <strong>Order Total: </strong><%= number_to_currency(@order.grand_total) %>
</p>

<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>
    <script src="http://checkout.stripe.com/checkout.js"
      class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="Order #<%= @order.id %>"
      data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>">
    </script>
  <% end %>
</div>

app/views/cart/order_complete.html.erb
<h1>Thank you for your order!</h1>

<p>
  Order #<%= @order.id %> will be shipping to you,
  <%= current_user.name %>, as soon as possible!
</p>

app/views/cart/view_order.html.erb
<div class="container">
  <div class="row">
    <h2>
      <% if user_signed_in? %>
      <%= current_user.name %>'s Cart
      <% else %>
      Guest's Cart
      <% end %>
    </h2>
  </div>
  <div class="row">
    <div class="card">
      <ul class="list-unstyled">

        <% total = 0 %>
        <% @line_items.each do |line_item| %>
        <li class="media my-2">
          <% if line_item.product.image.url.nil? %>
          <%= image_tag 'no-image.jpg', class: "cart-image mx-2" %>
          <% else %>
          <%= image_tag line_item.product.image.url, class: "cart-image mx-2" %>
          <% end %>
          <div class="media-body">
            <h5 class="mt-0">
              <%= line_item.product.name %>
            </h5>
            <div class="my-0">Qty: <%= line_item.quantity %> @ <%= number_to_currency line_item.product.price %> ea.</div>
            <div class="my-0"><strong><%= number_to_currency line_item.line_item_total %></strong></div>
            <div class="my-0"><%= link_to "Remove from Cart", delete_item_path(product_id: line_item.product.id), method: "post", class: "badge badge-warning" %></div>
          </div>
        </li>
        <% total += line_item.line_item_total %>
        <% end %>

      </ul>
      <div class="card-footer">
        <p>Subtotal: <%= current_order.line_items.pluck(:line_item_total).sum %></p>
        <p>Tax: <%= number_to_currency total * 0.07 %></p>
        <strong>Grand Total: </strong> <%= number_to_currency total + (total * 0.07) %><br>
      </div>
    </div>
  </div>

  <div class="row">
  </div>
  <div class="row mt-2">
    <%= link_to "EXTERMINATE", clear_cart_path, class: "btn btn-sm btn-danger mx-1" %>
    <%= link_to "Proceed to Checkout", checkout_path, class: "btn btn-sm btn-success mx-1" %>
  </div>
</div>