config/routes.rb
Rails.application.routes.draw do
  root 'storefront#all_items'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  get 'index' => 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  get 'clear_cart' => 'cart#clear_cart'
  post 'delete_item' => 'cart#delete_item'
  post 'order_complete' => 'cart#order_complete'
  devise_for :users
  resources :products
  resources :charges
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_line_item, only: :show
  authorize_resource except: :show
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description,
        :brand, :rating, :category_id, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="form-group">
    <%= form.select :category_id, @categories.collect { |c| [c.name, c.id] },
                  { include_blank: "Please select a category" } %>
  </div>

  <div class="form-group">
    <%= form.label :upload_product_image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<% if can? :create, Product %>
  <p><%= link_to 'New Product', new_product_path, class: "btn btn-sm btn-dark" %></p>
<% end %>

<table class="table table-striped table-hover table-dark">
  <thead class="thead-light">
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <!-- <th>Rating</th> -->
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <% @products.each do |product| %>
        <% if product.image.url.nil? %>
          <td><%= image_tag 'no-image.jpg', class: "img-responsive product-image" %></td>
        <% else %>
          <td><%= image_tag product.image.url, class: "img-responsive product-image" %></td>
        <% end %>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <!-- <td><%#= product.rating %></td> -->
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, Product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path, class: "btn btn-sm btn-dark" %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @product.image.url.nil? %>
    <%= image_tag 'no-image.jpg', class: "img-responsive product-image" %>
  <% else %>
    <%= image_tag @product.image.url, class: "img-responsive product-image" %>
  <% end %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<div class="col-md-6">
  <div class="card p-3">
    <%= form_for @line_item, url: add_to_cart_path do |f| %>
      <div class="form-group">
        <%= f.hidden_field :product_id, value: @product.id %>
      </div>

      <span class="form-group">
        <%= f.number_field :quantity, value: 1, min: 1, max: @product.quantity %>
      </span>

      <span class="form-group">
        <%= f.submit "Add to Cart", class: "btn btn-primary" %>
      </span>
    <% end %>
    <% if user_signed_in? %>
      <% if can? :manage, Product %>
        <div class="card-footer">
          <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-sm btn-warning" %> |
          <%= link_to "!Destroy!", @product, class: "btn btn-sm btn-danger label-alert", method: :delete, data: {confirm: "Confirm Delete Product"} %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>