config/routes.rb
Rails.application.routes.draw do
  root 'storefront#all_items'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  get 'index' => 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  get 'clear_cart' => 'cart#clear_cart'
  post 'delete_item' => 'cart#delete_item'
  post 'order_complete' => 'cart#order_complete'
  devise_for :users
  resources :products
  resources :charges
end

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-light bg-light mr-auto">
  <div class="container-fluid ">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <% if can? :create, Product %>
      <%= link_to 'New Product', new_product_path, class: "btn btn-sm btn-info" %>
    <% end %>
    <%# debugger %>
    <%= link_to " Cart (#{@cart_count ? @cart_count : 0})", view_order_path, class: "nav nav-link fa fa-shopping-cart" %>
    <div class="dropdown">
      <a href="#" class="nav nav-link dropdown-toggle" data-toggle="dropdown" role="button">Categories<span class="caret"></span></a>
      <ul class="dropdown-menu">
        <% @categories.each do |category| %>
          <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
        <% end %>
      </ul>
    </div>
    <div class="dropdown">
      <a href="#" class="nav nav-link dropdown-toggle" data-toggle="dropdown" role="button">Brands</span></a>
      <ul class="dropdown-menu">
        <% @brands.each do |brand| %>
          <li><%= link_to brand, branding_path(brand: brand) %></li>
        <% end %>
        <li><%= link_to 'All', root_path %></li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="#" class="nav nav-link dropdown-toggle" data-toggle="dropdown" role="button">
        <%= current_user.nil? ? "Guest" : current_user.name %>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav nav-link" %>
          </li>
          <li >
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'layouts/navbar' %>
    <%= yield %>

  </body>
</html>